# Site
name: "Tunna Duong"
title: "Tunna Duong"
description: "Blog chia sẻ kiến thức về lập trình và tâm lý học. Bởi Dương Tùng Anh"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: 
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'duongtunganhspace'
mailchimp-list: 'https://tunnaduong.us2.list-manage.com/subscribe?u=786678e91a79db202c071feb9&id=b63d0943bf'
include: ["_pages"]
permalink: /:title/
email: tunnaduong@gmail.com

# Authors
authors:
  tunna:
    name: Tunna
    display_name: Tunna
    gravatar: d87d84da08798fa90b2973e65a5bc38b
    email: tunna@tunnaduong.com
    web: https://tunnaduong.com/
    twitter: https://twitter.com/tunnaduong
    facebook: https://facebook.com/tunnaduong
    instagram: https://instagram.com/tunganh_handsome
    description: "Tác giả của blog Tunna Duong, một trang blog học tập và chia sẻ kiến thức. Chủ yếu viết về lập trình và tâm lý học. Rất lười viết lách. Mình thích cái gì thì mình viết ra thôi."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
